services:
  # Backend web service using Node.js native environment
  - type: web
    name: affirmation-app-backend
    env: node # Changed from docker to node
    repo: https://github.com/nikh-prin/affirmation-app-backend.git # Your GitHub repository
    region: oregon # or your preferred region
    plan: free # Update based on your needs
    branch: main # or your main branch name
    healthCheckPath: /api/health
    buildCommand: "npm install && npm run build" # Added for Node.js environment
    startCommand: "npm start" # Added for Node.js environment
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: affirmation-db
          property: connectionString
      - key: JWT_SECRET
        sync: false # This will be manually set in the Render dashboard

# PostgreSQL database
databases:
  - name: affirmation-db
    plan: free # Update based on your needs
    region: oregon # or your preferred region
    databaseName: affirmation_app
    user: affirmation_user
